### PR TITLE
Add use cases for sort feature

### LINKED ISSUE #149: Update DG in week 10

### PR DESCRIPTION
**Pull request by kumsssss**
1) Added use cases for sort by ascending quantity, descending quantity and expiry date.

### CODE REVIEW

**Review by Md-Fazil — COMMENTED** [review]
LGTM!

**Review by chewwh09 — COMMENTED** [review]
You can add some extensions. But it can be done at the later milestones. Other than that, LGTM!

**Review by Md-Fazil — COMMENTED** [review]
LGTM!

**Review by JayChenYJ — APPROVED** [review]
LGTM

**Pull request merged**
